/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.SistemaDeReservaciones.cPresentacion;

import com.SistemaDeReservaciones.cEntidad.Clientes;
import com.SistemaDeReservaciones.cEntidad.Factura;
import com.SistemaDeReservaciones.cEntidad.Habitaciones;
import com.SistemaDeReservaciones.cLogicaNegocio.ClientesLN;
import com.SistemaDeReservaciones.cLogicaNegocio.FacturaLN;
import com.SistemaDeReservaciones.cLogicaNegocio.HabitacionDeLujoLN;
import com.SistemaDeReservaciones.cLogicaNegocio.HabitacionSencillaLN;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class FrmFactura extends javax.swing.JFrame {

    Factura factu;
    Habitaciones habi;
    Clientes cliente;

    ClientesLN clienteLN;
    FacturaLN factuLN;
    HabitacionSencillaLN habiSLN;
    HabitacionDeLujoLN habiDLLN;

    int opcion = 0;
    DefaultTableModel modeloTabla = new DefaultTableModel();

    /**
     * Creates new form FrmFactura
     */
    public FrmFactura() {
        initComponents();
        setLocationRelativeTo(null);
        setLayout(null);

        factu = new Factura();
        cliente = new Clientes();
        habi = new Habitaciones();

        factuLN = new FacturaLN();
        habiSLN = new HabitacionSencillaLN();
        habiDLLN = new HabitacionDeLujoLN();
        clienteLN = new ClientesLN();

        txtIdFactura.setText(factuLN.consecutivoId() + "");

        crearColumna();
        cargarTabla();
    }

    public void crearColumna() {
        ArrayList<String> nombreColumna = new ArrayList<>();

        nombreColumna.add("ID Factura");
        nombreColumna.add("ID Cliente");
        nombreColumna.add("ID Habitacion");
        nombreColumna.add("Nombre");
        nombreColumna.add("Masajes");
        nombreColumna.add("Transporte");
        nombreColumna.add("Telefono");
        nombreColumna.add("Caja de Seguridad");
        nombreColumna.add("Precio habitacion");
        nombreColumna.add("Precio total");

        for (String columna : nombreColumna) {
            modeloTabla.addColumn(columna);
        }
        this.tabla.setModel(modeloTabla);
    }

    public void cargarTabla() {
        ArrayList<Factura> facturas = factuLN.consultar();

        ArrayList<Object[]> datos = new ArrayList<>();

        if (!facturas.isEmpty()) {
            for (Factura f : facturas) {
                Object[] factu = new Object[]{
                    f.getIdFactura(),
                    f.getIdCliente(),
                    f.getIdHabitacion(),
                    f.getNombrePersonaFactura(),
                    f.getCantidadMasajes(),
                    f.getCuantasVecesUsoTransporte(),
                    f.getCuantasVecesUsoTelefono(),
                    f.getCuantasVecesUsoCajaSeguridad(),
                    f.getPrecioHabitacion(),
                    f.getPrecioTotal()
                };
                datos.add(factu);
            }
            for (Object[] factu : datos) {
                modeloTabla.addRow(factu);
            }
            tabla.setModel(modeloTabla);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultarClientes = new javax.swing.JButton();
        btnConsultarHabitaciones = new javax.swing.JButton();
        btnMirarFactura = new javax.swing.JButton();
        btnConsultarDeLujo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdFactura = new javax.swing.JTextField();
        txtBuscarIdCliente = new javax.swing.JTextField();
        txtMasajes = new javax.swing.JTextField();
        txtTransporte = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCajaSeguridad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEliminar = new javax.swing.JTextField();
        txtModificar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIdHabitacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel1.setText("Registro factura");

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 102));
        btnLimpiar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 255, 102));
        btnAgregar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnAgregar.setText("Generar factura");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(255, 255, 51));
        btnModificar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 51));
        btnEliminar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsultarClientes.setBackground(new java.awt.Color(255, 255, 102));
        btnConsultarClientes.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnConsultarClientes.setText("Consultar clientes");
        btnConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClientesActionPerformed(evt);
            }
        });

        btnConsultarHabitaciones.setBackground(new java.awt.Color(255, 255, 102));
        btnConsultarHabitaciones.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnConsultarHabitaciones.setText("Consultar habitaciones sencillas");
        btnConsultarHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarHabitacionesActionPerformed(evt);
            }
        });

        btnMirarFactura.setBackground(new java.awt.Color(255, 255, 51));
        btnMirarFactura.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnMirarFactura.setText("Mirar factura por nombre");
        btnMirarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMirarFacturaActionPerformed(evt);
            }
        });

        btnConsultarDeLujo.setBackground(new java.awt.Color(255, 255, 102));
        btnConsultarDeLujo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnConsultarDeLujo.setText("Consultar habitaciones de lujo");
        btnConsultarDeLujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDeLujoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnMirarFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultarClientes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(386, 386, 386)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarDeLujo)
                    .addComponent(btnConsultarHabitaciones))
                .addGap(350, 350, 350))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnConsultarClientes)
                            .addComponent(btnMirarFactura)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnConsultarHabitaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultarDeLujo)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Factura :");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar ID Cliente :");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad de Masajes :");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cuantas veces uso el Transporte :");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cuantas veces uso el Telefono :");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cuantas veces uso la Caja de Seguridad :");

        txtIdFactura.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Eliminar :");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Modificar :");

        txtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Cliente :");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID Habitacion :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasajes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtBuscarIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCajaSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtIdCliente))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEliminar)
                                .addComponent(txtModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtBuscarIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMasajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCajaSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!vacioAgregar()) {
            factu = new Factura();

            factu.setIdFactura(Integer.parseInt(txtIdFactura.getText()));
            factu.setIdCliente(Integer.parseInt(txtIdCliente.getText()));
            factu.setIdHabitacion(Integer.parseInt(txtIdHabitacion.getText()));

            factu.setCantidadMasajes(Integer.parseInt(txtMasajes.getText()));
            factu.setCuantasVecesUsoTransporte(Integer.parseInt(txtTransporte.getText()));
            factu.setCuantasVecesUsoTelefono(Integer.parseInt(txtTelefono.getText()));
            factu.setCuantasVecesUsoCajaSeguridad(Integer.parseInt(txtCajaSeguridad.getText()));

            if (factuLN.verificarHabitacionDeLujo(factu.getIdHabitacion())) {

                if (factuLN.buscarIdHabitacionDeLujo(factu.getIdHabitacion())) {

                    if (factuLN.verificarFacturableDeLujo(factu.getIdHabitacion())) {

                        if (factuLN.buscarIdCliente(factu.getIdCliente())) {

                            factu.setPrecioTotal(factuLN.calcularUsos(factu.getCantidadMasajes(), factu.getCuantasVecesUsoTransporte(), factu.getCuantasVecesUsoCajaSeguridad(), factu.getCuantasVecesUsoTelefono(), habi.getCostoDeHabitacion()));
                            factu.setNombrePersonaFactura(factuLN.obtenerNombreLujo(factu.getIdHabitacion()));
                            factu.setPrecioHabitacion(factuLN.obtenerPrecioHabitacionLujosa(factu.getIdHabitacion()));
                            modeloTabla.setRowCount(0);
                            limpiarTodo();
                            JOptionPane.showMessageDialog(null, factuLN.agregarFactura(factu, true) ? "La factura se agrego con exito." : "No se agrego la factura");
                            txtIdFactura.setText(factuLN.consecutivoId() + "");
                            cargarTabla();
                        } else {
                            modeloTabla.setRowCount(0);
                            JOptionPane.showMessageDialog(null, "No existe id");
                            cargarTabla();
                        }
                    } else {
                        modeloTabla.setRowCount(0);
                        JOptionPane.showMessageDialog(null, "No se puede efectuar la factura de una habitacion que no esta reservada o ocupada");
                        cargarTabla();
                    }
                } else {
                    modeloTabla.setRowCount(0);
                    JOptionPane.showMessageDialog(null, "No se encontro habitacion");
                    cargarTabla();
                }
            } else {
                if (factuLN.buscarIdHabitacionSencilla(factu.getIdHabitacion())) {

                    if (factuLN.buscarIdHabitacionSencilla(factu.getIdHabitacion())) {

                        if (factuLN.buscarIdCliente(factu.getIdCliente())) {

                            factu.setPrecioTotal(factuLN.calcularUsos(factu.getCantidadMasajes(), factu.getCuantasVecesUsoTransporte(), factu.getCuantasVecesUsoCajaSeguridad(), factu.getCuantasVecesUsoTelefono(), habi.getCostoDeHabitacion()));
                            factu.setNombrePersonaFactura(factuLN.obtenerNombreSencilla(factu.getIdHabitacion()));
                            factu.setPrecioHabitacion(factuLN.obtenerPrecioHabitacionSencilla(factu.getIdHabitacion()));

                            limpiarTodo();

                            modeloTabla.setRowCount(0);
                            JOptionPane.showMessageDialog(null, factuLN.agregarFactura(factu, true) ? "La factura se agrego con exito." : "No se agrego la factura");
                            txtIdFactura.setText(factuLN.consecutivoId() + "");
                            cargarTabla();
                        } else {
                            modeloTabla.setRowCount(0);
                            JOptionPane.showMessageDialog(null, "No existe id");
                            cargarTabla();
                        }
                    } else {
                        modeloTabla.setRowCount(0);
                        JOptionPane.showMessageDialog(null, "No se puede efectuar la factura de una habitacion que no esta reservada o ocupada");
                        cargarTabla();
                    }
                } else {
                    modeloTabla.setRowCount(0);
                    JOptionPane.showMessageDialog(null, "No se encontro habitacion");
                    cargarTabla();
                }
            }
        } else {
            modeloTabla.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Rellene los campos vacios");
            cargarTabla();
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarTodo();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (!vacioModificar()) {
            factu = new Factura();
            factu.setIdFactura(Integer.parseInt(txtModificar.getText()));
            factu.setIdCliente(Integer.parseInt(txtIdCliente.getText()));
            factu.setCantidadMasajes(Integer.parseInt(txtMasajes.getText()));
            factu.setCuantasVecesUsoTransporte(Integer.parseInt(txtTransporte.getText()));
            factu.setCuantasVecesUsoTelefono(Integer.parseInt(txtTelefono.getText()));
            factu.setCuantasVecesUsoCajaSeguridad(Integer.parseInt(txtMasajes.getText()));

            limpiarTodo();

            if (factuLN.verificarHabitacionDeLujo(factu.getIdHabitacion())) {

                if (factuLN.buscarIdHabitacionDeLujo(factu.getIdHabitacion())) {

                    if (factuLN.verificarFacturableDeLujo(factu.getIdHabitacion())) {

                        if (factuLN.buscarIdCliente(factu.getIdCliente())) {

                            factu.setPrecioTotal(factuLN.calcularUsos(factu.getCantidadMasajes(), factu.getCuantasVecesUsoTransporte(), factu.getCuantasVecesUsoCajaSeguridad(), factu.getCuantasVecesUsoTelefono(), habi.getCostoDeHabitacion()));
                            factu.setNombrePersonaFactura(factuLN.obtenerNombreLujo(factu.getIdHabitacion()));
                            factu.setPrecioHabitacion(factuLN.obtenerPrecioHabitacionLujosa(factu.getIdHabitacion()));
                            modeloTabla.setRowCount(0);
                            JOptionPane.showMessageDialog(null, factuLN.agregarFactura(factu, true) ? "La factura se agrego con exito." : "No se agrego la factura");
                            txtIdFactura.setText(factuLN.consecutivoId() + "");
                            cargarTabla();
                        } else {
                            modeloTabla.setRowCount(0);
                            JOptionPane.showMessageDialog(null, "No existe id");
                            cargarTabla();
                        }
                    } else {
                        modeloTabla.setRowCount(0);
                        JOptionPane.showMessageDialog(null, "No se puede efectuar la factura de una habitacion que no esta reservada o ocupada");
                        cargarTabla();
                    }
                } else {
                    modeloTabla.setRowCount(0);
                    JOptionPane.showMessageDialog(null, "No se encontro habitacion");
                    cargarTabla();
                }
            } else {
                if (factuLN.buscarIdHabitacionSencilla(factu.getIdHabitacion())) {

                    if (factuLN.buscarIdHabitacionSencilla(factu.getIdHabitacion())) {

                        if (factuLN.buscarIdCliente(factu.getIdCliente())) {

                            factu.setPrecioTotal(factuLN.calcularUsos(factu.getCantidadMasajes(), factu.getCuantasVecesUsoTransporte(), factu.getCuantasVecesUsoCajaSeguridad(), factu.getCuantasVecesUsoTelefono(), habi.getCostoDeHabitacion()));
                            factu.setNombrePersonaFactura(factuLN.obtenerNombreSencilla(factu.getIdHabitacion()));
                            factu.setPrecioHabitacion(factuLN.obtenerPrecioHabitacionSencilla(factu.getIdHabitacion()));

                            limpiarTodo();

                            modeloTabla.setRowCount(0);
                            JOptionPane.showMessageDialog(null, factuLN.agregarFactura(factu, true) ? "La factura se agrego con exito." : "No se agrego la factura");
                            txtIdFactura.setText(factuLN.consecutivoId() + "");
                            cargarTabla();
                        } else {
                            modeloTabla.setRowCount(0);
                            JOptionPane.showMessageDialog(null, "No existe id");
                            cargarTabla();
                        }
                    } else {
                        modeloTabla.setRowCount(0);
                        JOptionPane.showMessageDialog(null, "No se puede efectuar la factura de una habitacion que no esta reservada o ocupada");
                        cargarTabla();
                    }
                } else {
                    modeloTabla.setRowCount(0);
                    JOptionPane.showMessageDialog(null, "No se encontro habitacion");
                    cargarTabla();
                }
            }
        } else {
            modeloTabla.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Llene los espacios en blanco.");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!vacioEliminar()) {
            factu = new Factura();

            factu.setIdFactura(Integer.parseInt(txtEliminar.getText()));
            limpiarTodo();
            modeloTabla.setRowCount(0);
            JOptionPane.showMessageDialog(null, factuLN.eliminarFactura(factu.getIdFactura()) ? "Se elimino factura" : "No se pudo eliminar");
            cargarTabla();
        } else {
            modeloTabla.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Rellene el campo vacio");
            cargarTabla();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClientesActionPerformed
        modeloTabla.setRowCount(0);
        FrmConsultaClientes frmConsult = new FrmConsultaClientes();
        frmConsult.setVisible(true);
        cargarTabla();// TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarClientesActionPerformed

    private void btnConsultarHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarHabitacionesActionPerformed
        modeloTabla.setRowCount(0);
        FrmConsultaHabitaciones frmHabi = new FrmConsultaHabitaciones();

        frmHabi.setVisible(true);
        cargarTabla();

// TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarHabitacionesActionPerformed

    private void btnMirarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMirarFacturaActionPerformed
        String nombre = JOptionPane.showInputDialog("Digite el nombre de la factura que desea consultar");

        JOptionPane.showMessageDialog(null, factuLN.buscarFacturaPorNombre(nombre).toArray());
// TODO add your handling code here:
    }//GEN-LAST:event_btnMirarFacturaActionPerformed

    private void btnConsultarDeLujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDeLujoActionPerformed
        modeloTabla.setRowCount(0);

        FrmConsultarHabitacionDeLujo frmHabiDL = new FrmConsultarHabitacionDeLujo();
        frmHabiDL.setVisible(true);

        cargarTabla();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarDeLujoActionPerformed

    public void limpiarTodo() {
        txtIdCliente.setText("");
        txtMasajes.setText("");
        txtTransporte.setText("");
        txtTelefono.setText("");
        txtCajaSeguridad.setText("");
        txtEliminar.setText("");
        txtModificar.setText("");
        txtBuscarIdCliente.setText("");
        txtIdHabitacion.setText("");
    }

    public boolean vacioAgregar() {
        boolean estaVacio = false;
        if (txtIdCliente.getText().equals("")
                || txtMasajes.getText().equals("")
                || txtTransporte.getText().equals("")
                || txtTelefono.getText().equals("")
                || txtCajaSeguridad.getText().equals("")
                || txtIdHabitacion.getText().equals("")) {
            estaVacio = true;
        }
        return estaVacio;
    }

    public boolean vacioModificar() {
        boolean estaVacio = false;
        if (txtModificar.getText().equals("")
                || txtIdCliente.getText().equals("")
                || txtMasajes.getText().equals("")
                || txtTransporte.getText().equals("")
                || txtTelefono.getText().equals("")
                || txtCajaSeguridad.getText().equals("")
                || txtIdHabitacion.getText().equals("")) {
            estaVacio = true;
        }
        return estaVacio;
    }

    public boolean vacioEliminar() {
        boolean estaVacio = false;
        if (txtEliminar.getText().equals("")) {
            estaVacio = true;
        }
        return estaVacio;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultarClientes;
    private javax.swing.JButton btnConsultarDeLujo;
    private javax.swing.JButton btnConsultarHabitaciones;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMirarFactura;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscarIdCliente;
    private javax.swing.JTextField txtCajaSeguridad;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdFactura;
    private javax.swing.JTextField txtIdHabitacion;
    private javax.swing.JTextField txtMasajes;
    private javax.swing.JTextField txtModificar;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTransporte;
    // End of variables declaration//GEN-END:variables
}
