/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.SistemaDeReservaciones.cPresentacion;

import com.SistemaDeReservaciones.cEntidad.Clientes;
import com.SistemaDeReservaciones.cEntidad.Habitaciones;
import com.SistemaDeReservaciones.cLogicaNegocio.ClientesLN;
import com.SistemaDeReservaciones.cLogicaNegocio.HabitacionDeLujoLN;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class FrmHabitacionDeLujo extends javax.swing.JFrame {

    HabitacionDeLujoLN habiLN;
    Habitaciones habi;

    ClientesLN clienteLN;
    Clientes cliente;

    DefaultTableModel modeloTabla = new DefaultTableModel();

    /**
     * Creates new form FrmHabitaciones
     */
    public FrmHabitacionDeLujo() {
        initComponents();
        setLayout(null);
        setLocationRelativeTo(null);
        habiLN = new HabitacionDeLujoLN();
        habi = new Habitaciones();
        clienteLN = new ClientesLN();
        cliente = new Clientes();

        txtIdHabitacion.setText(habiLN.idConsecutivo() + "");

        crearModeloColumna();
        cargarTabla();
    }

    public void cargarTabla() {
        ArrayList<Habitaciones> listaHabitacion = habiLN.consultar();

        ArrayList<Object[]> datos = new ArrayList<>();

        if (!listaHabitacion.isEmpty()) {
            for (Habitaciones h : listaHabitacion) {
                Object[] habi = new Object[]{
                    h.getIdHabitacion(),
                    h.getCostoDeHabitacion(),
                    h.getCantidadMaximaDePersonas(),
                    h.getPersonaQueReserva(),
                    h.getTipoDeCama(),
                    h.getAireAcondicionado(),
                    h.getEstadoDeHabitacion()
                };
                datos.add(habi);
            }
            for (Object[] habi : datos) {
                modeloTabla.addRow(habi);
            }
            tabla.setModel(modeloTabla);
        }
    }

    public void crearModeloColumna() {
        ArrayList<String> nombreColumna = new ArrayList<>();

        nombreColumna.add("ID Habitacion");
        nombreColumna.add("Costo");
        nombreColumna.add("CantidadPersonas");
        nombreColumna.add("Persona que reserva");
        nombreColumna.add("Tipo de cama");
        nombreColumna.add("Aire acondicionado");
        nombreColumna.add("Estado habitacion");

        for (String columna : nombreColumna) {
            modeloTabla.addColumn(columna);
        }
        this.tabla.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnMostrarReserva = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbEstadoHabitacion = new javax.swing.JComboBox<>();
        cbCantidadDePersonas = new javax.swing.JComboBox<>();
        cbTipoCama = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdHabitacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEliminar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtModificar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtReservar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));
        setForeground(new java.awt.Color(0, 204, 102));

        jPanel1.setBackground(new java.awt.Color(255, 51, 204));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Habitaciones de lujo");

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(51, 255, 51));
        btnAgregar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(102, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnReservar.setBackground(new java.awt.Color(255, 0, 255));
        btnReservar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(153, 51, 0));
        btnModificar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnMostrarReserva.setBackground(new java.awt.Color(255, 255, 102));
        btnMostrarReserva.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnMostrarReserva.setText("Mostrar Habitaciones Reservadas");
        btnMostrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReservar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(btnMostrarReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnConsultar)
                            .addComponent(jLabel1)
                            .addComponent(btnReservar)
                            .addComponent(btnEliminar)
                            .addComponent(btnModificar)
                            .addComponent(btnMostrarReserva))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        cbEstadoHabitacion.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        cbEstadoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de habitacion", "Disponible", "Ocupada", "Mantenimiento" }));
        cbEstadoHabitacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbEstadoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoHabitacionActionPerformed(evt);
            }
        });

        cbCantidadDePersonas.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        cbCantidadDePersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la cantidad de personas", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cbCantidadDePersonas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbCantidadDePersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCantidadDePersonasActionPerformed(evt);
            }
        });

        cbTipoCama.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        cbTipoCama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de cama", "1 cama matrimonial con aire", "2 camas matrimoniales con aire", "2 camas matrimoniales y 2 camarotes con aire" }));
        cbTipoCama.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbTipoCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoCamaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estado habitacion :");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad de personas :");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de cama :");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID habitacion :");

        txtIdHabitacion.setEditable(false);
        txtIdHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdHabitacionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 153));
        jLabel8.setText("ID Eliminar :");

        txtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 153));
        jLabel9.setText("ID Modificar :");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Reservar :");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID Cliente Que Reserva :");

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbTipoCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbCantidadDePersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(218, 218, 218)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtReservar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTipoCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbCantidadDePersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (verificarAgregar()) {
            habi = new Habitaciones();

            habi.setIdHabitacion(Integer.parseInt(txtIdHabitacion.getText()));
            habi.setPersonaQueReserva("No hay");
            habi.setEstadoDeHabitacion("Disponible");
            habi.setCantidadMaximaDePersonas(0);
            habi.setTipoDeCama("Ha disposicion");
            habi.setAireAcondicionado(true);

            limpiarTodo();
            modeloTabla.setRowCount(0);

            JOptionPane.showMessageDialog(null, habiLN.agregarHabitacion(habi, true) ? "Los datos se agregaron con exito" : "No se pudo agregar los datos");
            txtIdHabitacion.setText(habiLN.idConsecutivo() + "");
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "No puede agregar habitacion con datos");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        JOptionPane.showMessageDialog(null, clienteLN.consultar().toArray());
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        if (!verificarCampoVacioReservar()) {
            habi = new Habitaciones();

            habi.setIdHabitacion(Integer.parseInt(txtReservar.getText()));
            habi.setEstadoDeHabitacion("Reservada");
            habi.setCantidadMaximaDePersonas(Integer.parseInt((String) cbCantidadDePersonas.getSelectedItem()));
            habi.setTipoDeCama((String) cbTipoCama.getSelectedItem());
            cliente.setIdCliente(Integer.parseInt(txtIdCliente.getText()));

            if (habi.getTipoDeCama().equalsIgnoreCase("1 cama matrimonial con aire")) {
                habi.setCostoDeHabitacion(35000);

            } else if (habi.getTipoDeCama().equalsIgnoreCase("2 camas matrimoniales con aire")) {
                habi.setCostoDeHabitacion(65000);
            } else if (habi.getTipoDeCama().equalsIgnoreCase("2 camas matrimoniales y 2 camarotes con aire")) {
                habi.setCostoDeHabitacion(100000);
            }
            habi.setAireAcondicionado(true);

            limpiarTodo();

            JOptionPane.showMessageDialog(null, "El costo de la habitacion es : " + habi.getCostoDeHabitacion());

            modeloTabla.setRowCount(0);

            if (habiLN.buscarHabitacion(habi.getIdHabitacion())) {

                if (clienteLN.buscarIdCliente(cliente.getIdCliente())) {

                    if (habiLN.verificarDisponible(habi.getIdHabitacion())) {
                        limpiarTodo();
                        habi.setPersonaQueReserva(clienteLN.sacarNombreCliente(cliente.getIdCliente()));
                        modeloTabla.setRowCount(0);
                        JOptionPane.showMessageDialog(null, habiLN.modificarHabitacion(habi) ? "Se reservo con exito" : "No se pudo reservar");
                        cargarTabla();

                    } else {
                        modeloTabla.setRowCount(0);
                        JOptionPane.showMessageDialog(null, "No puede reservar una habitacion con un estado diferente a disponible");
                        cargarTabla();
                    }

                } else {
                    limpiarTodo();
                    modeloTabla.setRowCount(0);
                    JOptionPane.showMessageDialog(null, "No existe id, intente registrarse en el hotel");
                    cargarTabla();
                }
            } else {
                modeloTabla.setRowCount(0);
                JOptionPane.showMessageDialog(null, "No existe la habitacion");
                cargarTabla();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Asigne los datos correspondientes");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarActionPerformed

    private void txtIdHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdHabitacionActionPerformed

    private void txtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEliminarActionPerformed

    private void cbEstadoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoHabitacionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!verificarCampoVacioEliminar()) {
            habi = new Habitaciones();

            habi.setIdHabitacion(Integer.parseInt(txtEliminar.getText()));
            modeloTabla.setRowCount(0);
            JOptionPane.showMessageDialog(null, habiLN.eliminarHabitacion(habi.getIdHabitacion()) ? "Los datos se eliminaron con exito" : "Hubo un error");
            limpiarTodo();
            cargarTabla();
            if (!habiLN.eliminarHabitacion(habi.getIdHabitacion())) {
                limpiarTodo();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Rellene el campo vacio");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (!verificarCampoVacioModificar()) {

            habi = new Habitaciones();

            habi.setIdHabitacion(Integer.parseInt(txtModificar.getText()));
            habi.setEstadoDeHabitacion((String) cbEstadoHabitacion.getSelectedItem());
            habi.setCantidadMaximaDePersonas(Integer.parseInt((String) cbCantidadDePersonas.getSelectedItem()));
            habi.setTipoDeCama((String) cbTipoCama.getSelectedItem());

            if (habi.getTipoDeCama().equalsIgnoreCase("1 cama matrimonial con aire")) {
                habi.setCostoDeHabitacion(35000);

            } else if (habi.getTipoDeCama().equalsIgnoreCase("2 camas matrimoniales con aire")) {
                habi.setCostoDeHabitacion(65000);

            } else if (habi.getTipoDeCama().equalsIgnoreCase("2 camas matrimoniales y 2 camarotes con aire")) {
                habi.setCostoDeHabitacion(100000);
            }
            habi.setAireAcondicionado(true);

            limpiarTodo();

            JOptionPane.showMessageDialog(null, "El costo de la habitacion es : " + habi.getCostoDeHabitacion());

            modeloTabla.setRowCount(0);
            JOptionPane.showMessageDialog(null, habiLN.modificarHabitacion(habi) ? "Los datos se modificaron con exito" : "No se pudo agregar");

            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione las opciones");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbCantidadDePersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCantidadDePersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCantidadDePersonasActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        cliente.setIdCliente(Integer.parseInt(txtIdCliente.getText()));
        if (clienteLN.buscarIdCliente(cliente.getIdCliente())) {
            //txtPersonaQueReserva.setText(cliente.getNombre() + " " + cliente.getApellidoUno() + " " + cliente.getApellidoDos());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void cbTipoCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoCamaActionPerformed
        try {
            if (cbTipoCama.getSelectedItem().equals("1 cama matrimonial con aire")) {
                cbCantidadDePersonas.removeAllItems();
                cbCantidadDePersonas.addItem("Seleccione la cantidad de personas");
                cbCantidadDePersonas.addItem("1");
                cbCantidadDePersonas.addItem("2");
            } else if (cbTipoCama.getSelectedItem().equals("2 camas matrimoniales con aire")) {
                cbCantidadDePersonas.removeAllItems();
                cbCantidadDePersonas.addItem("Seleccione la cantidad de personas");
                cbCantidadDePersonas.addItem("1");
                cbCantidadDePersonas.addItem("2");
                cbCantidadDePersonas.addItem("3");
                cbCantidadDePersonas.addItem("4");
            } else if (cbTipoCama.getSelectedItem().equals("2 camas matrimoniales y 2 camarotes con aire")) {
                cbCantidadDePersonas.removeAllItems();
                cbCantidadDePersonas.addItem("Seleccione la cantidad de personas");
                cbCantidadDePersonas.addItem("1");
                cbCantidadDePersonas.addItem("2");
                cbCantidadDePersonas.addItem("3");
                cbCantidadDePersonas.addItem("4");
                cbCantidadDePersonas.addItem("5");
                cbCantidadDePersonas.addItem("6");
                cbCantidadDePersonas.addItem("7");
                cbCantidadDePersonas.addItem("8");
            }
        } catch (Exception e) {

        }
//    Seleccione el tipo de cama
//1 cama matrimonial
//2 camas matrimoniales
//2 camas matrimoniales y 2 camarotes// TODO add your handling code here:
    }//GEN-LAST:event_cbTipoCamaActionPerformed

    private void btnMostrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReservaActionPerformed
        modeloTabla.setRowCount(0);
        JOptionPane.showMessageDialog(null, habiLN.mostrarReservas().toArray());
        cargarTabla();// TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarReservaActionPerformed

    public void cargarHabitaciones() {
        cbEstadoHabitacion.addItem("Selecciones una habitacion");
    }

    public void actualizarTabla() {
        modeloTabla.setRowCount(0);
        cargarTabla();
    }

    public void limpiarTodo() {
        txtEliminar.setText("");
        txtReservar.setText("");
        txtModificar.setText("");
        txtIdCliente.setText("");
        cbTipoCama.removeAllItems();
        cbTipoCama.addItem("Seleccione el tipo de cama");
        cbTipoCama.addItem("1 cama matrimonial con aire");
        cbTipoCama.addItem("2 camas matrimoniales con aire");
        cbTipoCama.addItem("2 camas matrimoniales y 2 camarotes con aire");
        cbCantidadDePersonas.removeAllItems();
        cbCantidadDePersonas.addItem("Seleccione la cantidad de personas");
        cbCantidadDePersonas.addItem("1");
        cbCantidadDePersonas.addItem("2");
        cbCantidadDePersonas.addItem("3");
        cbCantidadDePersonas.addItem("4");
        cbCantidadDePersonas.addItem("5");
        cbCantidadDePersonas.addItem("6");
        cbCantidadDePersonas.addItem("7");
        cbCantidadDePersonas.addItem("8");
        cbEstadoHabitacion.removeAllItems();
        cbEstadoHabitacion.addItem("Seleccione el estado de la habitacion");
        cbEstadoHabitacion.addItem("Disponible");
        cbEstadoHabitacion.addItem("Ocupada");
        cbEstadoHabitacion.addItem("Mantenimiento");
    }

    public boolean verificarCampoVacioModificar() {
        boolean hayVacio = false;
        if (cbEstadoHabitacion.getSelectedItem().equals("Seleccione el tipo de habitacion")
                || cbCantidadDePersonas.getSelectedItem().equals("Seleccione la cantidad de personas")
                || cbTipoCama.getSelectedItem().equals("Seleccione un tipo de cama")
                //|| txtPersonaQueReserva.getText().equals("")
                || txtModificar.getText().isEmpty()) {
            hayVacio = true;

        }
        return hayVacio;
    }

    public boolean verificarCampoVacioReservar() {
        boolean hayVacio = false;
        if (cbCantidadDePersonas.getSelectedItem().equals("Seleccione la cantidad de personas")
                || cbTipoCama.getSelectedItem().equals("Seleccione un tipo de cama")
                || txtReservar.getText().isEmpty()
                || txtIdCliente.getText().isEmpty()) {
            hayVacio = true;

        }
        return hayVacio;
    }

    public boolean verificarCampoVacioEliminar() {
        boolean hayVacio = false;
        if (txtEliminar.getText().isEmpty()) {
            hayVacio = true;
        }
        return hayVacio;
    }

    public boolean verificarAgregar() {
        boolean sePuede = false;
        if (cbCantidadDePersonas.getSelectedItem().equals("Seleccione la cantidad de personas")
                || cbTipoCama.getSelectedItem().equals("Seleccione un tipo de cama")
                || cbEstadoHabitacion.getSelectedItem().equals("Seleccione el estado de la habitacion")) {
            sePuede = true;

        }
        return sePuede;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHabitacionDeLujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHabitacionDeLujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHabitacionDeLujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHabitacionDeLujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmHabitacionDeLujo().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarReserva;
    private javax.swing.JButton btnReservar;
    private javax.swing.JComboBox<String> cbCantidadDePersonas;
    private javax.swing.JComboBox<String> cbEstadoHabitacion;
    private javax.swing.JComboBox<String> cbTipoCama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdHabitacion;
    private javax.swing.JTextField txtModificar;
    private javax.swing.JTextField txtReservar;
    // End of variables declaration//GEN-END:variables
}
